name: easy-ffi
version: 0.0.1
category: Development, FFI, Foreign
synopsis: Cross-platform FFI toolkit.
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/easy-ffi

extra-libraries:
  - ffi

when:
  - condition: os(windows)
    extra-libraries:
      - kernel32

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 4.10

library:
  source-dirs: src
  exposed-modules:
    - Foreign.Easy
